@startuml
'https://plantuml.com/sequence-diagram

title View Epub UI

boundary "View Epub"
control Repository

[-> "View Epub": From Load Epub UI\nwith ID

"View Epub" -> Repository: get Epub\nwith ID
Repository -> "View Epub": Result<Epub>

alt is Ok
    alt First load
        "View Epub" -> "View Epub": display\ntitle
    else
        "View Epub" -> "View Epub": display\nprevious page
    end
else
    "View Epub" -> "View Epub": display\nerror message
end

' TODO: 1, List contents by spine
' TODO: 2, Embedded image

@enduml